### ISSUE TITLE
Got a question about OWIN-MixedAuth

### ISSUE THREAD

**Issue by arc95** [emf411/hello-world#2]
Hi @emf411. Sorry to ask the question here but wasn't sure how to reach you. I'm using the OWIN-MixedAuth library and have it working. Saw your post where you got it working with [automatic Windows logon](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/8#issuecomment-149985443) and also differentiating between those coming in from your network vs. those outside. I couldn't get that working, as posted [here](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/83#issue-240772842).

My solution was to remove the automatic Windows logon and add back the [Windows] button on the Login page. Now everyone is directed to the Login page. 

Any thoughts on my [question](https://github.com/MohammadYounes/OWIN-MixedAuth/issues/83#issue-240772842)? How did you get your app working so it worked well for external and internal peoploe + did automatic Windows logon for internals? Thanks.

**Comment by georgiaprogrammer** [comment]
Hello,

Yes I can definitely help you by explaining what I did. I was able to get it working as you described in your thread, where internal users are automatically authenticated and logged in through AD, and external users are redirected to the login page without seeing the credentials prompt.

I'm currently out of the office, but will be returning on Monday and I can send over my working code. I'll help you with getting it working in your app.

--Eric

________________________________

**Comment by arc95** [comment]
Thank you, @emf411 :1st_place_medal:

**Comment by arc95** [comment]
Hi @emf411, thanks for your offer to help. Trying to figure out how you can share your code. Maybe a secret Gist which you can delete later? I can also share my email.

**Comment by georgiaprogrammer** [comment]
I can post here.  There's nothing proprietary.  This should pretty much get you going, I'm not sure exactly where you are in your process so let me know if you have any questions!

**1. Startup.Auth.cs**

`

            var cookieOptions = new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                //LoginPath = new PathString("/Account/Login"),
                LoginPath = new PathString("/Account/WindowsLogin"),
                Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user logs in.
                    // This is a security feature which is used when you change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
                        validateInterval: TimeSpan.FromSeconds(30),
                        regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
                }
            };
            app.UseCookieAuthentication(cookieOptions);

            //Enable Mixed Authentication
            //As we are using LogonUserIdentity, its required to run in PipelineStage.PostAuthenticate
            //Register this after any middleware that uses stage marker PipelineStage.Authenticate
            //See http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline      
            app.UseMixedAuth(cookieOptions);

`


**2. AccountController.cs**

`

        //
        // GET: /Account/WindowsLogin
        [AllowAnonymous]
        public ActionResult WindowsLogin(string returnUrl)
        {
            //return new ChallengeResult("Windows", Url.Action("ExternalLoginCallback", "Account", new { ReturnUrl = returnUrl }));

            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
            HttpContext.User = new GenericPrincipal(new GenericIdentity(string.Empty), null);

            if (IsInternalUserHost)
            {
                return new ChallengeResult("Windows", Url.Action("WindowsLoginCallback", "Account", new { ReturnUrl = returnUrl }));
            }
            else
            {
                AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                HttpContext.User = new GenericPrincipal(new GenericIdentity(string.Empty), null);

                return RedirectToAction("Login", new { ReturnUrl = returnUrl });
            }

        }
        
        //
        // GET: /Account/WindowsLoginCallback
        [AllowAnonymous]
        public async Task<ActionResult> WindowsLoginCallback(string returnUrl)
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Login", new { ReturnUrl = returnUrl });
            }

            // Sign in the user with this external login provider if the user already has a login
            var user = await UserManager.FindAsync(loginInfo.Login);
            if (user != null)
            {
                //await SignInAsync(user, isPersistent: false);
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                return RedirectToLocal(returnUrl);
            }
            else
            {
                //Log the user out
                AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                HttpContext.User = new GenericPrincipal(new GenericIdentity(string.Empty), null);
                return RedirectToAction("Login", new { ReturnUrl = returnUrl });
            }
        }

`

**Comment by arc95** [comment]
Thanks, @emf411! How did you set `IsInternalUserHost`? 

I used the following to determine if someone is internal/external:

```c#
public static bool IsIPPrivate(string ipAddress)
{
	var ipParts = ipAddress.Split(new[] { "." }, StringSplitOptions.RemoveEmptyEntries)
							 .Select(int.Parse).ToArray();
	var isDebug = System.Diagnostics.Debugger.IsAttached;

	if (ipParts[0] == 10 ||
		(isDebug && (ipParts[0] == 192 && ipParts[1] == 168) ||
		(ipParts[0] == 172 && (ipParts[1] >= 16 && ipParts[1] <= 31))))
		{
			return true;
		}
	return false;
}

// https://stackoverflow.com/a/20194511/177416
/// <summary>
/// method to get Client ip address
/// </summary>
/// <param name="GetLan"> set to true if want to get local(LAN) Connected ip address</param>
/// <returns></returns>
public static string GetVisitorIPAddress(bool GetLan = false)
{
	string visitorIPAddress = HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

	if (String.IsNullOrEmpty(visitorIPAddress))
		visitorIPAddress = HttpContext.Current.Request.ServerVariables["REMOTE_ADDR"];

	if (string.IsNullOrEmpty(visitorIPAddress))
		visitorIPAddress = HttpContext.Current.Request.UserHostAddress;

	if (string.IsNullOrEmpty(visitorIPAddress) || visitorIPAddress.Trim() == "::1")
	{
		GetLan = true;
		visitorIPAddress = string.Empty;
	}

	if (GetLan && string.IsNullOrEmpty(visitorIPAddress))
	{
		//This is for Local(LAN) Connected ID Address
		string stringHostName = Dns.GetHostName();
		//Get Ip Host Entry
		IPHostEntry ipHostEntries = Dns.GetHostEntry(stringHostName);
		//Get Ip Address From The Ip Host Entry Address List
		IPAddress[] arrIpAddress = ipHostEntries.AddressList;

		try
		{
			visitorIPAddress = arrIpAddress[arrIpAddress.Length - 2].ToString();
		}
		catch
		{
			try
			{
				visitorIPAddress = arrIpAddress[0].ToString();
			}
			catch
			{
				try
				{
					arrIpAddress = Dns.GetHostAddresses(stringHostName);
					visitorIPAddress = arrIpAddress[0].ToString();
				}
				catch
				{
					visitorIPAddress = "127.0.0.1";
				}
			}
		}

	}
	return visitorIPAddress;
}
```

**Comment by georgiaprogrammer** [comment]
I wrote a simple function to do that:

`

       /// <summary>
        /// This returns true when the user host is determined to be internal.
        /// </summary>
        public static bool IsInternalUserHost
        {
            get
            {
                string userHostName = HttpContext.Current.Request.UserHostName;
                string userHostAddress = HttpContext.Current.Request.UserHostAddress;

                //Do your logic here
                //return true; or return false;

            }
        }

`

**Comment by arc95** [comment]
Thanks, @emf411! A challenge I'm having is determining who's internal and who's external. If I connect to the site via my phone (which isn't on the network), it thinks I'm internal and brings up the challenge popup.

**Comment by georgiaprogrammer** [comment]
@arc95, your function looks good.  Here is actually my full solution for IsInternalUserHost, I use a stored proc on the backend to get my list of internal user host names/ip addresses:

`

        /// <summary>
        /// This returns true when the user host is determined to be internal.
        /// </summary>
        public static bool IsInternalUserHost
        {
            get
            {
                string userHostName = HttpContext.Current.Request.UserHostName;
                string userHostAddress = HttpContext.Current.Request.UserHostAddress;

                ApplicationDbContext context = new ApplicationDbContext();
                List<InternalUserHostViewModel> internalUserHostAddress = context.Database.SqlQuery<InternalUserHostViewModel>(@"
                        EXEC dbo.usp_GetInternalUserHost
                    ").ToList<InternalUserHostViewModel>();

                context.Dispose();

                return UserHostIsInternal(userHostName, userHostAddress, internalUserHostAddress);
            }
        }

        /// <summary>
        /// This returns true when the user host is determined to be internal.
        /// </summary>
        /// <param name="userHostName"> The Name of the User Host, i.e. "localhost".</param>
        /// <param name="userHostAddress"> The IP Address of the User Host, i.e "127.0.0.1".</param>
        /// <param name="internalUserHostAddress"> A list of internal user hosts.</param>
        public static bool UserHostIsInternal(string userHostName, string userHostAddress, List<InternalUserHostViewModel> internalUserHostAddress)
        {
            bool returnVal = false;
            bool exitFor = false;

            foreach (var item in internalUserHostAddress)
            {
                switch (item.ComparisonType.ToLower().Trim())
                {
                    case "equals":
                        if (!string.IsNullOrEmpty(item.UserHostName))
                        {
                            if (userHostName.Equals(item.UserHostName))
                            {
                                returnVal = item.ForceExternal ? false : true;
                                exitFor = true;
                            }
                        }
                        else if (!string.IsNullOrEmpty(item.UserHostAddress))
                        {
                            if (userHostAddress.Equals(item.UserHostAddress))
                            {
                                returnVal = item.ForceExternal ? false : true;
                                exitFor = true;
                            }
                        }
                        break;

                    case "startswith":
                        if (!string.IsNullOrEmpty(item.UserHostName))
                        {
                            if (userHostName.StartsWith(item.UserHostName))
                            {
                                returnVal = item.ForceExternal ? false : true;
                                exitFor = true;
                            }
                        }
                        else if (!string.IsNullOrEmpty(item.UserHostAddress))
                        {
                            if (userHostAddress.StartsWith(item.UserHostAddress))
                            {
                                returnVal = item.ForceExternal ? false : true;
                                exitFor = true;
                            }
                        }
                        break;

                    default:
                        break;
                }

                if (exitFor == true) break;
            }

            return returnVal;
        }

`

Here is my InternalUserHostViewModel

`

    public class InternalUserHostViewModel
    {
        public string UserHostAddress { get; set; }
        public string UserHostName { get; set; }
        public string ComparisonType { get; set; }
        public bool ForceExternal { get; set; }
        public string Notes { get; set; }

    }

`

**Comment by georgiaprogrammer** [comment]
@arc95, for the external challenge popup that you're getting on your phone, do you have a 401.html file in the root of your site?  If not, you'll need to create one with the following content:

```

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <meta http-equiv="refresh" content="0;URL='/Account/Login'" />
</head>
<body>
    Invalid credentials
</body>
</html>


```

Additionally, you'll need to implement the RegisterMixedAuth() logic to hook to the application's EndRequest event:

```

        /// <summary>
        /// Adds a mixed-authentication middleware support.
        /// </summary>
        /// <remarks>
        /// This is required to enable the modification of the fake status code.
        /// </remarks>
        /// <param name="app">The HttpApplication instance.</param>
        public static void RegisterMixedAuth(this HttpApplication app)
        {
            app.EndRequest += (object sender, EventArgs e) =>
            {
                if (app.Context.Response.StatusCode == MixedAuthConstants.FakeStatusCode)
                {
                    if (IsInternalUserHost)
                    {
                        //proceed with the challenge
                        app.Context.Response.StatusCode = 401;
                        app.Context.Response.SubStatusCode = 2;
                    }
                    else
                    {
                        //redirect to login page.
                        app.Context.Response.StatusCode = 401;
                        app.Context.Response.SubStatusCode = 2;
                    }
                }
            };

        }

```

**Comment by arc95** [comment]
Yeah, I'm missing the above. Thanks, @emf411. Where do you call the above custom `RegisterMixedAuth()` method? And do you call the same property on `AccountController` to get `IsInternalUserHost`? 

Currently, I have this in my `Global.asax.cs` file, which registers the default mixed auth:

```c#
public MvcApplication()
{
	this.RegisterMixedAuth();
}
```

**Comment by georgiaprogrammer** [comment]
@arc95, it goes in your Global.asax.cs:

```
        public MvcApplication()
        {
            this.RegisterMixedAuth();
        }
```

**Comment by arc95** [comment]
Thanks, @emf411. Your innermost IF/ELSE do the same thing. Is that correct? Thinking the ELSE needs to be:

```c#
app.Context.Response.StatusCode = 302;
app.Context.Response.RedirectLocation = HttpRuntime.AppDomainAppVirtualPath + "/Account/Login";
```

**Comment by georgiaprogrammer** [comment]
@arc95, yes it actually does look like the if/else are doing exactly the same thing, I must have left that redundant code behind during my original testing.  You can just change it to this:

```
            app.EndRequest += (object sender, EventArgs e) =>
            {
                if (app.Context.Response.StatusCode == MixedAuthConstants.FakeStatusCode)
                {
                    app.Context.Response.StatusCode = 401;
                    app.Context.Response.SubStatusCode = 2;
                }
            };
```

You may also need to add the following to your Web.config in the <system.webServer> section:

```
    <httpErrors errorMode="Custom">
      <remove statusCode="401" />
      <error statusCode="401" path="401.html" responseMode="File" />
    </httpErrors>
```

**Comment by arc95** [comment]
Thanks, @emf411. Got all of it wired up. Weird problem: When I call `System.Web.HttpContext.Current.Request.UserHostAddress` from the getter of `IsInternalUserHost`, it returns an internal `10.xxx.xxx.xxx` address -- even when I'm on my phone! Had someone else hit it from their phone and it returns the same IP address, which is probably the address of the server where this is being run. What the heck?

**Comment by georgiaprogrammer** [comment]
Hmm, is your phone connected to your company's WiFi?

**Comment by arc95** [comment]
Nope. None of our phones are. And yet friends are returning the same result. More here: https://stackoverflow.com/questions/45020640/client-ip-address-returns-the-same-internal-network-address

**Comment by georgiaprogrammer** [comment]
@arc95, not really sure on that one.. could be a web server setup related issue (routing/nat/etc), what are you running?  IIS?

**Comment by arc95** [comment]
Yes, but we're using a load balancer, which is probably screwing up the original address.

**Comment by arc95** [comment]
Thanks for your help, @emf411! The issue was with the load balancer; it gave an internal IP to all traffic, so no way to differentiate internal from external. There's a way to at least split the traffic into two internal IP addresses based on whether it's internal/external; we hope they'll make that change for us. 

Otherwise, we'll just redirect users to Login and be done with it.

**Comment by arc95** [comment]
@emf411 Got all of it working! The trick was to add an HTTP header on the Netscaler containing the client IP address. We can then read it via 

```c#
var clientIP = HttpContext.Current.Request.Headers["x-forwarded-for"];
```
Thanks again for all your help and patience with me! I think I drove you and MohammadYounes crazy :)

**Comment by georgiaprogrammer** [comment]
@arc95 you're welcome, that's great news!  Glad to hear everything is working!!
